apiVersion: v1
kind: Namespace
metadata:
  name: expensetracker-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-tracker-pod # Base POD name
  namespace: expensetracker-system
spec:
  selector:
    matchLabels:
      app: expensetracker # Selector for POD name search.
  template:
    metadata:
      labels:
        app: expensetracker
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      # expensetracker-api container configuration
      - name: e-tracker-api
        image: 36044735/expensetracker:v1.1.0
        ports:
        - name: e-tracker-api
          containerPort: 8000
        # readinessProbe: # readiness probes mark the service available to accept traffic.
        #   httpGet:
        #     path: /debug/readiness
        #     port: 4000
        #   initialDelaySeconds: 15
        #   periodSeconds: 15
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 2
        # livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
        #   httpGet:
        #     path: /debug/liveness
        #     port: 4000
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 2
        env:
        - name: SALES_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_host
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_PODNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_NAMESPACE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBERNETES_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-service
  namespace: expensetracker-system
spec:
  type: ClusterIP
  selector:
    app: expensetracker
  ports:
  - name: e-tracker-api
    port: 8000
    targetPort: e-tracker-api